server:
  port: 7000

spring:
  cloud:
    config:
      server:
        bootstrap: false
        git:
          clone-on-start: true
          uri: https://jdiaz495@bitbucket.org/jdiaz495/config-git.git
          default-label: master
          username: jdiaz495
          password: VnUsE4rDtmPrhLfGCJek