apiVersion: v1
kind: Service
metadata:
    name: "bootcampcluster-cb8e"
    labels:
        app: "bootcampcluster-cb8e"
spec:
    type: LoadBalancer
    ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP
      name: http
    selector:
        app: "bootcampcluster-cb8e"