name: Build and deploy on AKS
on:
  push:
    branches:
      - master

env:
  APP_NAME: config-server
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true

      - name: Build with Maven
        run: mvn clean package

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image to ACR
        run: |
          docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t nttdatabootcampacr.azurecr.io/bootcampcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
          docker push nttdatabootcampacr.azurecr.io/bootcampcluster:${{ github.sha }}
