name: Build and deploy on AKS
on:
  push:
    branches:
      - master

env:
  APP_NAME: config-server
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true

      - name: Build with Maven
        run: mvn clean package

  containerization:
    name: Containerization
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Container build and push to an Azure Container Registry (ACR)
      - run: |
        docker build . -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: containerization
    steps:
      # Set the target AKS cluster.
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          resource-group: ${{ secrets.CLUSTER_RESOURCE_GROUP }}

      # Create namespace if doesn't exist
      - run: |
        kubectl create namespace ${{ secrets.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -

      - uses: Azure/k8s-create-secret@v1.1
        with:
          container-registry-url: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: bootcamp-secret

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}'
          files: '["*.yaml"]'
        env:
          REPOSITORY_NAME: ${{ secrets.REGISTRY_NAME }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

      # Deploy app to AKS
      - uses: azure/k8s-deploy@v1.4
        with:
          manifests: |
            ${{ github.workspace }}/deployment.yaml
            ${{ github.workspace }}/service.yaml
          images: |
            ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
          namespace: ${{ secrets.NAMESPACE }}
          imagepullsecrets: |
            bootcamp-secret